apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: yakd-dashboard
    kubernetes.io/minikube-addons: yakd-dashboard
    addonmanager.kubernetes.io/mode: Reconcile
  name: yakd-dashboard
  namespace: yakd-dashboard
