name: hide-minikube-bot-comments
on: issue_comment
permissions:
  contents: read

jobs:
  hide-comments:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-22.04
    steps:
      - uses: spowelljr/hide-minikube-bot-comments@6ef419ab40a17cf0bdc1f98f2442bf19b72d911d
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
